config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end

  # resources :admins do
  #   get 'profile', on: :collection, as: 'profile' # Changes the path to /admins/profile
  #   get 'profiles', on: :collection, as: 'profiles' # Changes the path to /admins/profiles
  # end
  resources :members
  resources :teams
  resources :activities do
    member do
      post 'sign_up'
      get 'participants'
      delete 'remove_participant/:participant_id', to: 'activities#remove_participant', as: 'remove_participant'
    end
  end
  resources :feedbacks
  resources :home
  get 'calendar', to: 'activities#calendar', as: 'calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/feedback.rb
# frozen_string_literal: true

# Feedback model represents feedback entries in the application.
# It includes validations to ensure that feedback is always present.
# Additionally, it uses callbacks to set default values for name and email
# before validation, ensuring that every feedback has this information,
# even if it is provided as 'Anonymous' or 'N/A'. This model encapsulates
# the behavior and data related to user feedback, ensuring data integrity
# and providing a layer of business logic for handling feedback entries.
class Feedback < ApplicationRecord
  validates :feedback, presence: true

  # Set default values before validation if not present
  before_validation :set_defaults, on: %i[create update]

  private

  def set_defaults
    self.name = 'Anonymous' if name.blank?
    self.email = 'N/A' if email.blank?
  end
end

app/controllers/feedbacks_controller.rb
# frozen_string_literal: true

# FeedbacksController manages all actions related to Feedback resources.
# This includes creating, updating, deleting, and displaying feedback.
# It inherits from ApplicationController to leverage common functionality
# across the application.
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[show edit update destroy]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show; end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit; end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to feedback_url(@feedback), notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to feedback_url(@feedback), notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def feedback_params
    params.require(:feedback).permit(:feedback, :email, :name)
  end
end

app/helpers/feedbacks_helper.rb
# frozen_string_literal: true

# FeedbacksHelper provides a collection of helper methods related to the feedback feature
# within the application. These methods assist in presenting feedback data in the views,
# performing common formatting tasks, and generating reusable HTML elements specific to
# feedback handling. This module aims to simplify the views by encapsulating view logic,
# thereby making the codebase more maintainable and the user interface more consistent.
module FeedbacksHelper
end

app/views/feedbacks/_feedback.html.erb
<div id="<%= dom_id feedback %>">
  <p>
    <strong>Message:</strong>
    <%= feedback.feedback %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= feedback.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= feedback.name %>
  </p>

</div>

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input">
    <%= form.label :feedback, style: "display: block" %>
    <%= form.text_field :feedback %>
  </div>

  <div class="input">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="input">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="input">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<style>
  h1 {
    margin-left: 10px;
  }

  p {
    margin-left: 11px;
  }

  .input {
    margin-left: 11px;
    margin-top: 5px;
  }

  .link {
    margin-left: 10px;
    margin-top: 5px;
  }
</style>

<h1>Edit Feedback</h1>

<div class="link">
  <%= link_to "Back", feedbacks_path %>
</div>

<%= render "form", feedback: @feedback %>

app/views/feedbacks/index.html.erb
<style>
  h1 {
    margin-left: 10px;
  }

  p {
    margin-left: 11px;
  }

  .feedback-table {
    border-collapse: collapse;
    width: 80%;
    margin-left: auto;
    margin-right: auto;
  }

  .feedback-table th, .feedback-table td {
    border: 1px solid #dddddd;
    text-align: center;
    padding: 8px;
  }

  .feedback-table th {
    background-color: #f2f2f2;
  }

  .button {
    display: inline-block;
    padding: 5px 10px;
    margin-left: 11px;
    background-color: #8c2a00;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.2s;
  }
  
  .button:hover {
    background-color: #672000;
    color: white;
  }
</style>

<h1>Feedback</h1>

<% if !current_member&.is_admin? %>
  <p>Fill out the form below if you have any feedback you would like to share with us. Any feedback is appreciated!</p>
<% end %>

<%= link_to "New feedback", new_feedback_path, class: "button" %>

<% if current_member&.is_admin? %>
  <table class="feedback-table">
    <thead>
      <tr>
        <th>Feedback</th>
        <th>Email</th>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @feedbacks.each do |feedback| %>
        <tr id="feedback_<%= feedback.id %>">
          <td><%= feedback.feedback %></td>
          <td><%= feedback.email %></td>
          <td><%= feedback.name %></td>
          <td><%= link_to "Edit", edit_feedback_path(feedback) %></td>
          <td><%= button_to "Destroy", feedback, method: :delete, remote: true, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/feedbacks/new.html.erb
<style>
  h1 {
    margin-left: 10px;
  }

  p {
    margin-left: 11px;
  }

  .input {
    margin-left: 11px;
    margin-top: 5px;
  }

  .link {
    margin-left: 10px;
    margin-top: 5px;
  }
</style>

<div class="link">
  <%= link_to("Back", feedbacks_path, :class => 'back-link') %>
</div>

<h1>New feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

app/views/feedbacks/show.html.erb
<style>
  h1 {
    margin-left: 10px;
  }

  p {
    margin-left: 11px;
  }

  .input {
    margin-left: 11px;
    margin-top: 5px;
  }

  .link {
    margin-left: 10px;
    margin-top: 5px;
  }
</style>

<div class="link">
  <%= link_to("Back", feedbacks_path, :class => 'back-link') %>
</div>

<p>Once you leave this page you can no longer edit or delete this feedback unless you ask an admin!</p>

<%= render @feedback %>

<div class="input">
  <%= link_to "Edit", edit_feedback_path(@feedback) %>
  <%= button_to "Destroy this feedback", @feedback, method: :delete %>
</div>