config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end

  # resources :admins do
  #   get 'profile', on: :collection, as: 'profile' # Changes the path to /admins/profile
  #   get 'profiles', on: :collection, as: 'profiles' # Changes the path to /admins/profiles
  # end
  resources :members
  resources :teams
  resources :activities do
    member do
      post 'sign_up'
      get 'participants'
      delete 'remove_participant/:participant_id', to: 'activities#remove_participant', as: 'remove_participant'
    end
  end
  resources :feedbacks
  resources :home
  get 'calendar', to: 'activities#calendar', as: 'calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/activity.rb
# Activity model represents an event or activity within the application.
# It includes various fields such as event_name, start_time, end_time,
# location, description, activity_type, and points, each of which
# is validated for presence to ensure that all activities have complete and
# meaningful information. This model inherits from ApplicationRecord, which
# provides it with a set of functionalities for interacting with the application's database.
class Activity < ApplicationRecord
  validates :event_name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :activity_type, presence: true
  validates :points, presence: true

  has_many :participations, dependent: :destroy
  has_many :members, through: :participations
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

# ActivitiesController manages all actions related to Activity resources.
# This includes creating, updating, deleting, and displaying activities.
# It inherits from ApplicationController to leverage common functionality
# across the application.
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  before_action :authenticate_member! # Assumes you have some authentication method
  layout 'modal_layout', only: [:new, :show] # specify other actions if needed

  def calendar
    @activities = Activity.where(
        start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
    @activity = Activity.new # Or however you need to define @activity
    @activities = Activity.all # Assuming you need to list activities
  end


  def participants
    @activity = Activity.find(params[:id])
    @participants = @activity.members
  end

  def remove_participant
    activity = Activity.find(params[:id])
    participant = activity.members.find(params[:participant_id])
    if participant
      new_points_total = participant.points - activity.points
      participant.update(points: new_points_total)
  
      activity.members.delete(participant)
      flash[:notice] = "Participant was successfully removed."
    else
      flash[:alert] = "Participant could not be found."
    end
    redirect_to participants_activity_path(activity)
  end
  

  def sign_up
    @activity = Activity.find(params[:id])
    participation = Participation.new(member: current_member, activity: @activity)
  
    if participation.save
      current_member.points += @activity.points
      if current_member.save
        flash[:notice] = 'You have successfully signed up for the activity and earned points.'
      else
        flash[:alert] = current_member.errors.full_messages.to_sentence
      end
    else
      flash[:alert] = participation.errors.full_messages.to_sentence
    end
    redirect_to @activity
  end

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show; end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:event_name, :start_time, :end_time, :location, :description, :activity_type, :points)
  end

end

app/helpers/activities_helper.rb
# frozen_string_literal: true

# The ActivitiesHelper module is designed to provide view helper methods
# related to activity management within the application. These helper methods
# can be used to format activity data, generate HTML snippets, or provide
# utility functions that facilitate the presentation of activities in views.
# This module enhances the separation of concerns by encapsulating view-specific
# logic, making the views cleaner and more maintainable.
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id(activity) %>" class="activity">
  <p>
    <strong>Event name:</strong>
    <%= activity.event_name %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= activity.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= activity.end_time %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= activity.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= activity.description %>
  </p>

  <p>
    <strong>Activity type:</strong>
    <%= activity.activity_type %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= activity.points %>
  </p>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event_name, style: "display: block" %>
    <%= form.text_field :event_name %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :activity_type, style: "display: block" %>
    <%= form.text_field :activity_type %>
  </div>

  <div>
    <%= form.label :points, style: "display: block" %>
    <%= form.text_field :points %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/calendar.html.erb
<script>
document.addEventListener("DOMContentLoaded", function() {
  document.getElementById('popup_link').addEventListener('click', function(e) {
    e.preventDefault();
    fetch('<%= new_activity_path %>')
      .then(response => response.text())
      .then(html => {
        document.getElementById('new-activity-form').innerHTML = html;
      });
  });
});

document.addEventListener("DOMContentLoaded", function() {
  document.querySelectorAll('.activity-link').forEach(item => {
    item.addEventListener('click', function(e) {
      e.preventDefault();
      const url = this.getAttribute('data-url'); // URL from the data attribute
      fetch(url)
        .then(response => response.text())
        .then(html => {
          document.getElementById('activity-detail-content').innerHTML = html;
        });
    });
  });
});

</script>


<%= link_to 'Back to Homepage', root_path %><br />

<div class="container mt-5 text-center">
    <h1>Calendar</h1>
    <%= month_calendar(events: @activities) do |date, activities| %>
        <div class="day">
            <%= date %>
        </div>
        <% activities.each do |activity| %>
            <div class="card-header">
                <h5 class="card-title">
                    <%= link_to activity.event_name, activity_path(activity), 
            class: 'activity-link', 
            'data-bs-toggle': 'modal', 
            'data-bs-target': '#activityDetailModal',
            'data-url': activity_path(activity) %>

                </h5>
            </div>
        <% end %>
    <% end %>
    <% if current_member&.is_admin? %>
      <%= link_to 'New Activity', activities_path, id: 'popup_link', 'data-bs-toggle': 'modal', 'data-bs-target': '#activitiesModal' %>
    <% end %>
</div>

<!-- New Activity Modal -->
<div class="modal fade" id="activitiesModal" tabindex="-1" aria-labelledby="activitiesModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="activitiesModalLabel">Activities</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <!-- Container for new activity form -->
        <div id="new-activity-form">
          <!-- Content from new.html.erb will be loaded here -->
        </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Activity Detail Modal -->
<div class="modal fade" id="activityDetailModal" tabindex="-1" aria-labelledby="activityDetailModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="activityDetailModalLabel">Activity Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="activity-detail-content">
        <!-- Activity content will be loaded here -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<%= link_to 'Back to Homepage', root_path %><br />

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
    <p>
      <%= link_to "Show this activity", activity %>
    </p>
  <% end %>
</div>
<% if current_member&.is_admin? %>
  <%= link_to "New activity", new_activity_path %>
<% end %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/participants.html.erb
<h1>Participants for <%= @activity.event_name %></h1>

<ul>
  <% @participants.each do |participant| %>
    <li>
      <%= participant.first_name %> <%= participant.last_name %>
      <%= button_to 'Remove', remove_participant_activity_path(id: @activity.id, participant_id: participant.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back to Activity', activity_path(@activity) %>

app/views/activities/show.html.erb
<%= render @activity %>

<div>
  <%= link_to 'View Participants', participants_activity_path(@activity), class: "btn btn-info" %> | 
  <%= link_to "Back to activities", activities_path %>
  <% if current_member&.is_admin? %>
    <%= link_to "Edit this activity", edit_activity_path(@activity) %> | 
    <%= button_to "Destroy this activity", @activity, method: :delete %>
  <% end %>
  <%= button_to 'Sign Up', sign_up_activity_path(@activity), method: :post, class: "btn btn-primary" %>
</div>