config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end

  # resources :admins do
  #   get 'profile', on: :collection, as: 'profile' # Changes the path to /admins/profile
  #   get 'profiles', on: :collection, as: 'profiles' # Changes the path to /admins/profiles
  # end
  resources :members
  resources :teams
  resources :activities do
    member do
      post 'sign_up'
      get 'participants'
      delete 'remove_participant/:participant_id', to: 'activities#remove_participant', as: 'remove_participant'
    end
  end
  resources :feedbacks
  resources :home
  get 'calendar', to: 'activities#calendar', as: 'calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amcp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .flash__alert   { color: red; }
      .flash__notice  { color: blue; }
      .flash__success { color: green; }
      .navbar.bg-primary {
        background-color: #8c2a00 !important;
      }
      .navbar-logo {
        height: 50px; 
        width: 50px; 
        border-radius: 50%;
        object-fit: cover; 
        margin-left:10px;
      }
      .navbar-nav .nav-link:hover {
        color: white !important;
      }
      .nav-item.active .nav-link {
        color: white;
      }

      .nav-item-right{
        margin-right: 0px !important;
        margin-left: auto !important;
      }
    </style>  
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag 'amcplogo.png', alt: 'AMCP Logo', class: 'navbar-logo' %>
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if request.path.include?('/feedbacks') %>">
        <%= link_to 'Feedback', feedbacks_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if request.path.include?('/activities') %>">
        <%= link_to 'Activities', activities_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if request.path.include?('/calendar') %>">
        <%= link_to 'Calendar', calendar_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if request.path.include?('/teams') %>">
        <%= link_to 'Teams', teams_path, class: 'nav-link' %>
      </li>
      <% if current_member&.is_admin? %>
        <li class="nav-item <%= 'active' if request.path.include?('/members') %>">
          <%= link_to 'Members', members_path, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Flywire', 'https://tamu.estore.flywire.com/products/amcp-membership-local-dues-57716', target: '_blank', rel: 'noopener noreferrer', class: 'nav-link'  %>
      </li>

    </ul>
    <% if current_member %>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item nav-item-right">
          <%= link_to 'Sign Out', destroy_member_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

  <% if flash.any? %>
    <% flash.each do |key, value| -%>
      <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
    <% end -%>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/modal_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amcp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .flash__alert   { color: red; }
      .flash__notice  { color: blue; }
      .flash__success { color: green; }
      .navbar.bg-primary {
        background-color: #8c2a00 !important;
      }
      .navbar-logo {
        height: 50px; 
        width: 50px; 
        border-radius: 50%;
        object-fit: cover; 
        margin-left:10px;
      }
      .navbar-nav .nav-link:hover {
        color: white !important;
      }
      .nav-item.active .nav-link {
        color: white;
      }

      .nav-item-right{
        margin-right: 0px !important;
        margin-left: auto !important;
      }
    </style>  
  </head>

  <body>
  <% if flash.any? %>
    <% flash.each do |key, value| -%>
      <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
    <% end -%>
  <% end %>
    <%= yield %>
  </body>
</html>